title: ML-TIL
description: Vision-Language Models · Paper Reviews · ML Notes
author: jungminhong
github_username: jungminhong123

# 기본 테마 설정
# theme: Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: dark
search: true
show_excerpts: true
paginate: 5


# 사이드바
author_profile: true
sidebar:
  nav: "main"

# 시간/날짜 포맷
timezone: Asia/Seoul
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 링크 자동화
permalink: /:categories/:year-:month-:day-:title/

# 기본 색상 테마 (minima 내장 옵션)
minima:
  skin: classic
  date_format: "%Y-%m-%d"

social_links:
  github: welovecherry
  linkedin: https://www.linkedin.com/in/jungmin-hong-887632336/

# 카테고리 페이지를 만들고 싶을 때
collections:
  posts:
    output: true 